---
title: "Biostat 212a In Class Quiz"
subtitle: " "
author: "Dr. Jin Zhou"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    theme: cosmo
    embed-resources: true
    number-sections: false
    toc: false
    toc-depth: 4
    toc-location: left
    code-fold: false
engine: knitr
knitr:
  opts_chunk: 
    fig.align: 'center'
    # fig.width: 6
    # fig.height: 4
    message: FALSE
    cache: false
---

### 1. Is linear regression a classification method?  

### 2. Is linear regression a parametric or non-parametric method?

### 3. What are the assumptions for linear regression?

### 4. Which method we used in linear regression lectures for parameter estimation?

### 5. How to interpret the coefficients in linear regression?

### 6. Can you list 2 methods for variable selection in the linear regression?

### 7. How to diagnose the model fit in linear regression?

### 8. For a two level factor variable, how many dummy variables we need to create? how about 3-level factor?

### 9. Explain what is "colinearity" regression?

### 10. Which test can you use to determin whether a subset of the predictors among $X_1, X_2, \ldots, X_p$ is useful in predicting the response? 

### 11. What is the difference between "forward selection" and "backward selection" in variable selection?



